import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';
import { jsPDF } from 'npm:jspdf@2.5.1';
import 'npm:jspdf-autotable@3.8.2';

// Helper function to format currency
const formatCurrency = (amount) => {
    return `BDT ${(amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

// Helper to get display name (English preferred)
const getDisplayName = (item) => {
    return item.english_item_name || item.item_name || 'Unknown Item';
};

// Department display names
const getDepartmentName = (dept) => {
    const names = {
        'boibari': 'Boibari.com - Books & Publications',
        'prodhan_com_e_commerce': 'Prodhan.com - E-Commerce'
    };
    return names[dept] || dept;
};

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();

        if (!user) {
            return Response.json({ error: 'Unauthorized' }, { status: 401 });
        }

        // Parse request body for department filter
        let department = 'all';
        try {
            const body = await req.json();
            department = body.department || 'all';
        } catch (e) {
            // No body or invalid JSON, use default
        }

        const inventoryItems = await base44.asServiceRole.entities.Inventory.list();

        // Filter by department if specified
        const filteredInventory = department === 'all' 
            ? inventoryItems 
            : inventoryItems.filter(item => item.department === department);

        // Get low stock items
        const lowStockItems = filteredInventory.filter(item => 
            (item.current_stock || 0) <= (item.minimum_stock || 0)
        );

        // Sort by urgency (shortfall percentage)
        lowStockItems.sort((a, b) => {
            const aShortfall = ((a.minimum_stock || 0) - (a.current_stock || 0)) / (a.minimum_stock || 1);
            const bShortfall = ((b.minimum_stock || 0) - (b.current_stock || 0)) / (b.minimum_stock || 1);
            return bShortfall - aShortfall;
        });

        const doc = new jsPDF('landscape');
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        
        // Modern Header
        doc.setFillColor(239, 68, 68); // Red
        doc.rect(0, 0, pageWidth, 35, 'F');
        
        // Title
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont(undefined, 'bold');
        doc.text('LOW STOCK ALERT REPORT', 14, 18);
        
        // Subtitle
        doc.setFontSize(11);
        doc.setFont(undefined, 'normal');
        const deptText = department === 'all' ? 'All Departments' : getDepartmentName(department);
        doc.text(deptText, 14, 28);

        // Report metadata
        doc.setFontSize(10);
        doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, pageWidth - 14, 18, { align: 'right' });
        doc.text(`Generated by: ${user.full_name || user.email}`, pageWidth - 14, 28, { align: 'right' });

        doc.setTextColor(0, 0, 0);

        // Statistics
        const outOfStockCount = lowStockItems.filter(item => (item.current_stock || 0) <= 0).length;
        const criticalCount = lowStockItems.filter(item => 
            (item.current_stock || 0) > 0 && 
            (item.current_stock || 0) < (item.minimum_stock || 0) / 2
        ).length;
        const warningCount = lowStockItems.length - outOfStockCount - criticalCount;

        // Summary Box
        doc.setFillColor(254, 242, 242); // Red-50
        doc.rect(10, 42, pageWidth - 20, 25, 'F');
        doc.setDrawColor(254, 202, 202);
        doc.rect(10, 42, pageWidth - 20, 25, 'S');

        doc.setFontSize(12);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(153, 27, 27);
        doc.text('ALERT SUMMARY', 14, 52);

        doc.setFontSize(10);
        const summaryY = 60;
        const colWidth = (pageWidth - 28) / 4;

        doc.setTextColor(51, 65, 85);
        doc.text('Total Alerts', 14, summaryY);
        doc.setFont(undefined, 'normal');
        doc.text(lowStockItems.length.toString(), 14, summaryY + 5);

        doc.setFont(undefined, 'bold');
        doc.text('Out of Stock', 14 + colWidth, summaryY);
        doc.setTextColor(239, 68, 68);
        doc.setFont(undefined, 'normal');
        doc.text(outOfStockCount.toString(), 14 + colWidth, summaryY + 5);

        doc.setTextColor(51, 65, 85);
        doc.setFont(undefined, 'bold');
        doc.text('Critical Level', 14 + colWidth * 2, summaryY);
        doc.setTextColor(245, 158, 11);
        doc.setFont(undefined, 'normal');
        doc.text(criticalCount.toString(), 14 + colWidth * 2, summaryY + 5);

        doc.setTextColor(51, 65, 85);
        doc.setFont(undefined, 'bold');
        doc.text('Warning Level', 14 + colWidth * 3, summaryY);
        doc.setTextColor(234, 179, 8);
        doc.setFont(undefined, 'normal');
        doc.text(warningCount.toString(), 14 + colWidth * 3, summaryY + 5);

        doc.setTextColor(0, 0, 0);

        if (lowStockItems.length === 0) {
            doc.setFontSize(14);
            doc.setTextColor(16, 185, 129);
            doc.text("All items are above minimum stock levels. No alerts at this time.", 14, 85);
        } else {
            const tableColumn = [
                "Product Name", 
                "Category",
                "Department",
                "Current Stock", 
                "Minimum Stock", 
                "Shortfall",
                "Reorder Point",
                "Lead Time (Days)",
                "Supplier",
                "Status"
            ];
            const tableRows = [];

            lowStockItems.forEach(item => {
                const shortfall = (item.minimum_stock || 0) - (item.current_stock || 0);
                const currentStock = item.current_stock || 0;
                const minStock = item.minimum_stock || 0;
                
                let status = 'Warning';
                if (currentStock <= 0) status = 'OUT OF STOCK';
                else if (currentStock < minStock / 2) status = 'Critical';

                tableRows.push([
                    getDisplayName(item),
                    item.category || 'N/A',
                    item.department === 'boibari' ? 'Boibari' : 'Prodhan.com',
                    currentStock,
                    minStock,
                    shortfall,
                    item.reorder_point || minStock,
                    item.supplier_lead_time_days || 7,
                    item.supplier_name || 'Not Set',
                    status
                ]);
            });

            doc.autoTable({
                head: [tableColumn],
                body: tableRows,
                startY: 72,
                styles: { 
                    fontSize: 8,
                    cellPadding: 2,
                    overflow: 'linebreak'
                },
                headStyles: { 
                    fillColor: [239, 68, 68],
                    textColor: 255,
                    fontStyle: 'bold',
                    halign: 'center'
                },
                alternateRowStyles: {
                    fillColor: [254, 242, 242]
                },
                columnStyles: {
                    0: { cellWidth: 45 },
                    3: { halign: 'center' },
                    4: { halign: 'center' },
                    5: { halign: 'center' },
                    6: { halign: 'center' },
                    7: { halign: 'center' },
                    9: { halign: 'center', fontStyle: 'bold' }
                },
                didParseCell: function(data) {
                    if (data.column.index === 9 && data.section === 'body') {
                        const status = data.cell.raw;
                        if (status === 'OUT OF STOCK') {
                            data.cell.styles.textColor = [239, 68, 68];
                        } else if (status === 'Critical') {
                            data.cell.styles.textColor = [245, 158, 11];
                        } else {
                            data.cell.styles.textColor = [234, 179, 8];
                        }
                    }
                },
                didDrawPage: function(data) {
                    doc.setFontSize(8);
                    doc.setTextColor(148, 163, 184);
                    doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageWidth - 14, pageHeight - 10, { align: 'right' });
                    doc.text('Confidential - Bee ERP System', 14, pageHeight - 10);
                }
            });
        }
        
        const pdfBytes = doc.output('arraybuffer');
        const filename = department === 'all' 
            ? 'low_stock_alert_report_all.pdf'
            : `low_stock_alert_report_${department}.pdf`;

        return new Response(pdfBytes, {
            status: 200,
            headers: { 
                'Content-Type': 'application/pdf', 
                'Content-Disposition': `attachment; filename=${filename}` 
            }
        });

    } catch (error) {
        console.error('Error generating report:', error);
        return Response.json({ error: error.message }, { status: 500 });
    }
});