import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';
import { jsPDF } from 'npm:jspdf@2.5.1';
import 'npm:jspdf-autotable@3.8.2';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Fetch inventory items
    const inventoryItems = await base44.asServiceRole.entities.Inventory.list();
    
    // Fetch all inventory movements for return/damage data
    const movements = await base44.asServiceRole.entities.InventoryMovement.filter(
      { movement_type: { $in: ['return', 'adjustment'] } },
      '-movement_date',
      5000
    );

    // Aggregate movements by item
    const movementsByItem = {};
    movements.forEach(m => {
      if (!movementsByItem[m.inventory_item_id]) {
        movementsByItem[m.inventory_item_id] = {
          total_returned_qty: 0,
          total_damaged_qty: 0,
          total_returned_value: 0,
          total_damaged_value: 0
        };
      }

      const data = movementsByItem[m.inventory_item_id];
      
      if (m.movement_type === 'return') {
        data.total_returned_qty += Math.abs(m.quantity || 0);
        data.total_returned_value += Math.abs(m.total_value || 0);
      } else if (m.movement_type === 'adjustment' || m.reference_type === 'damage') {
        data.total_damaged_qty += Math.abs(m.quantity || 0);
        data.total_damaged_value += Math.abs(m.total_value || 0);
      }
    });
    
    const doc = new jsPDF('landscape'); // Landscape for more columns
    
    doc.setFontSize(20);
    doc.text('Stock Valuation Report', 14, 22);
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30);
    doc.text(`Generated by: ${user.full_name}`, 14, 36);

    const tableColumn = [
      "Item Name", 
      "Category", 
      "Stock", 
      "Returned", 
      "Damaged",
      "Price (৳)", 
      "Stock Value (৳)",
      "Return Loss (৳)",
      "Damage Loss (৳)"
    ];
    
    const tableRows = [];
    let grandTotal = 0;
    let totalReturnLoss = 0;
    let totalDamageLoss = 0;

    inventoryItems.forEach(item => {
      const movementData = movementsByItem[item.id] || {
        total_returned_qty: 0,
        total_damaged_qty: 0,
        total_returned_value: 0,
        total_damaged_value: 0
      };

      const stockValue = (item.current_stock || 0) * (item.purchase_price || 0);
      grandTotal += stockValue;
      totalReturnLoss += movementData.total_returned_value;
      totalDamageLoss += movementData.total_damaged_value;

      const itemData = [
        item.item_name,
        item.category,
        item.current_stock || 0,
        movementData.total_returned_qty,
        movementData.total_damaged_qty,
        (item.purchase_price || 0).toFixed(2),
        stockValue.toFixed(2),
        movementData.total_returned_value.toFixed(2),
        movementData.total_damaged_value.toFixed(2)
      ];
      tableRows.push(itemData);
    });

    doc.autoTable({
      head: [tableColumn],
      body: tableRows,
      startY: 42,
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [139, 92, 246], textColor: 255 }
    });
    
    const finalY = doc.lastAutoTable.finalY || 10;
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text(`Total Stock Value: ৳${grandTotal.toLocaleString()}`, 14, finalY + 10);
    doc.text(`Total Return Loss: ৳${totalReturnLoss.toLocaleString()}`, 14, finalY + 18);
    doc.text(`Total Damage Loss: ৳${totalDamageLoss.toLocaleString()}`, 14, finalY + 26);
    doc.setTextColor(220, 38, 38);
    doc.text(`Net Loss: ৳${(totalReturnLoss + totalDamageLoss).toLocaleString()}`, 14, finalY + 34);
    
    const pdfBytes = doc.output('arraybuffer');
    return new Response(pdfBytes, {
      status: 200,
      headers: { 
        'Content-Type': 'application/pdf', 
        'Content-Disposition': 'attachment; filename=stock_valuation_with_losses.pdf' 
      }
    });

  } catch (error) {
    console.error('Error generating report:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});