// Printable / downloadable expense documents: Invoice and MD Requisition.
// Opens a clean print window; the user can print or "Save as PDF".

const bdt = (n) =>
  'BDT ' + Number(n || 0).toLocaleString('en-BD', { maximumFractionDigits: 2 });

const fmtDate = (d) => {
  try {
    return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  } catch {
    return '';
  }
};

const COMPANY = {
  name: 'ZYPRA ERP',
  tagline: 'Business Suite',
  address: 'Dhaka, Bangladesh',
};

const baseStyles = `
  * { box-sizing: border-box; font-family: 'Segoe UI', Arial, sans-serif; }
  body { margin: 0; padding: 40px; color: #1e293b; }
  .doc { max-width: 720px; margin: 0 auto; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #6d28d9; padding-bottom: 16px; }
  .brand { font-size: 26px; font-weight: 800; color: #6d28d9; }
  .brand small { display:block; font-size: 12px; color:#64748b; font-weight:500; letter-spacing:1px; }
  .title { text-align: right; }
  .title h1 { margin: 0; font-size: 22px; letter-spacing: 1px; }
  .title .num { color:#64748b; font-size: 13px; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin: 24px 0; }
  th, td { text-align: left; padding: 10px 12px; font-size: 14px; }
  thead th { background:#f1f5f9; border-bottom: 2px solid #e2e8f0; }
  tbody td { border-bottom: 1px solid #eef2f7; }
  .right { text-align: right; }
  .meta { display:flex; gap:40px; margin-top: 8px; font-size: 13px; }
  .meta div b { display:block; color:#64748b; font-weight:600; margin-bottom:2px; }
  .total { font-size: 18px; font-weight: 800; color:#6d28d9; }
  .sign-row { display:flex; justify-content: space-between; margin-top: 70px; }
  .sign { width: 30%; text-align:center; }
  .sign .line { border-top: 1.5px solid #475569; margin-bottom: 6px; }
  .sign small { color:#64748b; }
  .stamp { margin-top: 10px; display:inline-block; padding:6px 14px; border:2px solid #16a34a; color:#16a34a; border-radius:6px; font-weight:700; transform: rotate(-6deg); }
  .footer { margin-top: 50px; text-align:center; color:#94a3b8; font-size:12px; }
  @media print { body { padding: 0; } .noprint { display:none; } }
`;

function openPrint(html) {
  const w = window.open('', '_blank', 'width=820,height=1000');
  if (!w) {
    alert('Please allow popups to print/download the document.');
    return;
  }
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
}

export function printExpenseInvoice(ex, me) {
  const html = `<!doctype html><html><head><meta charset="utf-8">
    <title>Invoice ${ex.invoiceNumber || ex.id}</title><style>${baseStyles}</style></head>
    <body><div class="doc">
      <div class="head">
        <div class="brand">${COMPANY.name}<small>${COMPANY.tagline} · ${COMPANY.address}</small></div>
        <div class="title"><h1>EXPENSE INVOICE</h1>
          <div class="num">No: ${ex.invoiceNumber || '—'}</div>
          <div class="num">Date: ${fmtDate(ex.date)}</div>
        </div>
      </div>
      <div class="meta">
        <div><b>Category</b>${ex.category}${ex.subCategory ? ' / ' + ex.subCategory : ''}</div>
        <div><b>Department</b>${ex.department?.name || '—'}</div>
        <div><b>Payment</b>${(ex.paymentMethod || '—').replace(/_/g, ' ')}</div>
        <div><b>Status</b>${ex.status}</div>
      </div>
      <table>
        <thead><tr><th>Description</th><th class="right">Amount</th></tr></thead>
        <tbody>
          <tr><td>${ex.description || ''}</td><td class="right">${bdt(ex.amount)}</td></tr>
        </tbody>
        <tfoot><tr><td class="right total">Total</td><td class="right total">${bdt(ex.amount)}</td></tr></tfoot>
      </table>
      <div class="sign-row">
        <div class="sign"><div class="line"></div><small>Prepared By</small></div>
        <div class="sign"><div class="line"></div><small>Approved By (Admin)</small></div>
        <div class="sign"><div class="line"></div><small>Accounts</small></div>
      </div>
      <div class="footer">Generated by ${COMPANY.name} on ${fmtDate(new Date())}</div>
    </div></body></html>`;
  openPrint(html);
}

export function printRequisition(ex, me) {
  const signed = ex.requisitionStatus === 'signed';
  const html = `<!doctype html><html><head><meta charset="utf-8">
    <title>Requisition ${ex.requisitionNumber || ex.id}</title><style>${baseStyles}</style></head>
    <body><div class="doc">
      <div class="head">
        <div class="brand">${COMPANY.name}<small>${COMPANY.tagline} · ${COMPANY.address}</small></div>
        <div class="title"><h1>FUND REQUISITION</h1>
          <div class="num">No: ${ex.requisitionNumber || '—'}</div>
          <div class="num">Date: ${fmtDate(ex.date)}</div>
        </div>
      </div>
      <p style="margin-top:24px;font-size:14px;">
        This requisition is raised for approval and release of funds against the expense detailed below.
      </p>
      <table>
        <thead><tr><th>Particulars</th><th>Department</th><th class="right">Amount</th></tr></thead>
        <tbody>
          <tr>
            <td>${ex.category}${ex.subCategory ? ' / ' + ex.subCategory : ''}<br><span style="color:#64748b;font-size:12px">${ex.description || ''}</span></td>
            <td>${ex.department?.name || '—'}</td>
            <td class="right">${bdt(ex.amount)}</td>
          </tr>
        </tbody>
        <tfoot><tr><td></td><td class="right total">Total</td><td class="right total">${bdt(ex.amount)}</td></tr></tfoot>
      </table>
      <div class="meta">
        <div><b>Linked Invoice</b>${ex.invoiceNumber || '—'}</div>
        <div><b>Admin Approval</b>${ex.status === 'APPROVED' ? 'Approved' : ex.status}</div>
        <div><b>MD Status</b>${signed ? 'Signed' : 'Pending'}</div>
      </div>
      <div class="sign-row">
        <div class="sign"><div class="line"></div><small>Requested By</small></div>
        <div class="sign"><div class="line"></div><small>Verified By (Admin)</small></div>
        <div class="sign">
          <div class="line"></div><small>Managing Director</small>
          ${signed ? `<div class="stamp">SIGNED</div><div style="font-size:11px;color:#64748b;margin-top:4px">${ex.mdApprovedByName || ''} · ${fmtDate(ex.mdApprovedAt)}</div>` : ''}
        </div>
      </div>
      <div class="footer">Generated by ${COMPANY.name} on ${fmtDate(new Date())}</div>
    </div></body></html>`;
  openPrint(html);
}
