import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';
import { jsPDF } from 'npm:jspdf@2.5.1';
import 'npm:jspdf-autotable@3.8.2';

// Helper function to format currency
const formatCurrency = (amount) => {
    return `BDT ${(amount || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

// Helper to get display name (English preferred)
const getDisplayName = (item) => {
    return item.english_item_name || item.item_name || 'Unknown Item';
};

// Department display names
const getDepartmentName = (dept) => {
    const names = {
        'boibari': 'Boibari.com - Books & Publications',
        'prodhan_com_e_commerce': 'Prodhan.com - E-Commerce'
    };
    return names[dept] || dept;
};

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();

        if (!user) {
            return Response.json({ error: 'Unauthorized' }, { status: 401 });
        }

        // Parse request body for department filter
        let department = 'all';
        try {
            const body = await req.json();
            department = body.department || 'all';
        } catch (e) {
            // No body or invalid JSON, use default
        }

        const [inventoryItems, movements] = await Promise.all([
            base44.asServiceRole.entities.Inventory.list(),
            base44.asServiceRole.entities.InventoryMovement.list()
        ]);

        // Filter by department if specified
        const filteredInventory = department === 'all' 
            ? inventoryItems 
            : inventoryItems.filter(item => item.department === department);

        // Process movement data
        const movementsByItem = {};
        movements.forEach(m => {
            if (!movementsByItem[m.inventory_item_id]) {
                movementsByItem[m.inventory_item_id] = {
                    total_returned_qty: 0,
                    total_damaged_qty: 0,
                    total_returned_value: 0,
                    total_damaged_value: 0
                };
            }

            const movementData = movementsByItem[m.inventory_item_id];
            
            if (m.movement_type === 'return' || m.reference_type === 'return') {
                movementData.total_returned_qty += Math.abs(m.quantity || 0);
                movementData.total_returned_value += Math.abs(m.total_value || 0);
            } else if (m.movement_type === 'adjustment' || m.reference_type === 'damage') {
                movementData.total_damaged_qty += Math.abs(m.quantity || 0);
                movementData.total_damaged_value += Math.abs(m.total_value || 0);
            }
        });

        const doc = new jsPDF('landscape');
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        
        // Modern Header with gradient effect simulation
        doc.setFillColor(79, 70, 229); // Indigo
        doc.rect(0, 0, pageWidth, 35, 'F');
        
        // Title
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont(undefined, 'bold');
        doc.text('STOCK VALUATION REPORT', 14, 18);
        
        // Subtitle with department info
        doc.setFontSize(11);
        doc.setFont(undefined, 'normal');
        const deptText = department === 'all' ? 'All Departments' : getDepartmentName(department);
        doc.text(deptText, 14, 28);

        // Report metadata on the right
        doc.setFontSize(10);
        doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, pageWidth - 14, 18, { align: 'right' });
        doc.text(`Generated by: ${user.full_name || user.email}`, pageWidth - 14, 28, { align: 'right' });

        // Reset text color
        doc.setTextColor(0, 0, 0);

        // Calculate statistics
        let grandTotal = 0;
        let totalReturned = 0;
        let totalDamaged = 0;
        let totalItems = filteredInventory.length;
        let lowStockCount = 0;
        let outOfStockCount = 0;

        const tableRows = [];

        filteredInventory.forEach(item => {
            const stockValue = (item.current_stock || 0) * (item.purchase_price || 0);
            const returnedQty = movementsByItem[item.id]?.total_returned_qty || 0;
            const damagedQty = movementsByItem[item.id]?.total_damaged_qty || 0;
            const returnedValue = movementsByItem[item.id]?.total_returned_value || 0;
            const damagedValue = movementsByItem[item.id]?.total_damaged_value || 0;
            const profitMargin = item.purchase_price > 0 
                ? (((item.selling_price || 0) - item.purchase_price) / item.purchase_price * 100).toFixed(1)
                : 0;

            grandTotal += stockValue;
            totalReturned += returnedValue;
            totalDamaged += damagedValue;

            if ((item.current_stock || 0) <= 0) outOfStockCount++;
            else if ((item.current_stock || 0) < (item.minimum_stock || 0)) lowStockCount++;

            tableRows.push([
                getDisplayName(item),
                item.category || 'N/A',
                item.current_stock || 0,
                formatCurrency(item.purchase_price),
                formatCurrency(item.selling_price),
                formatCurrency(stockValue),
                `${profitMargin}%`,
                `${returnedQty} (${formatCurrency(returnedValue)})`,
                `${damagedQty} (${formatCurrency(damagedValue)})`
            ]);
        });

        // Executive Summary Section
        doc.setFillColor(248, 250, 252); // Light gray
        doc.rect(10, 42, pageWidth - 20, 28, 'F');
        doc.setDrawColor(226, 232, 240);
        doc.rect(10, 42, pageWidth - 20, 28, 'S');

        doc.setFontSize(12);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(51, 65, 85);
        doc.text('EXECUTIVE SUMMARY', 14, 52);

        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        const summaryY = 62;
        const colWidth = (pageWidth - 28) / 5;

        // Summary metrics
        doc.setFont(undefined, 'bold');
        doc.text('Total Items', 14, summaryY);
        doc.setFont(undefined, 'normal');
        doc.text(totalItems.toString(), 14, summaryY + 6);

        doc.setFont(undefined, 'bold');
        doc.text('Total Stock Value', 14 + colWidth, summaryY);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(16, 185, 129); // Green
        doc.text(formatCurrency(grandTotal), 14 + colWidth, summaryY + 6);
        doc.setTextColor(51, 65, 85);

        doc.setFont(undefined, 'bold');
        doc.text('Low Stock Items', 14 + colWidth * 2, summaryY);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(245, 158, 11); // Amber
        doc.text(lowStockCount.toString(), 14 + colWidth * 2, summaryY + 6);
        doc.setTextColor(51, 65, 85);

        doc.setFont(undefined, 'bold');
        doc.text('Out of Stock', 14 + colWidth * 3, summaryY);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(239, 68, 68); // Red
        doc.text(outOfStockCount.toString(), 14 + colWidth * 3, summaryY + 6);
        doc.setTextColor(51, 65, 85);

        doc.setFont(undefined, 'bold');
        doc.text('Total Losses', 14 + colWidth * 4, summaryY);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(239, 68, 68);
        doc.text(formatCurrency(totalReturned + totalDamaged), 14 + colWidth * 4, summaryY + 6);
        doc.setTextColor(0, 0, 0);

        // Data Table
        const tableColumn = [
            "Product Name", 
            "Category", 
            "Stock", 
            "Cost Price", 
            "Sell Price",
            "Stock Value",
            "Margin",
            "Returns",
            "Damages"
        ];

        doc.autoTable({
            head: [tableColumn],
            body: tableRows,
            startY: 75,
            styles: { 
                fontSize: 8,
                cellPadding: 3,
                overflow: 'linebreak'
            },
            headStyles: { 
                fillColor: [79, 70, 229],
                textColor: 255,
                fontStyle: 'bold',
                halign: 'center'
            },
            alternateRowStyles: {
                fillColor: [248, 250, 252]
            },
            columnStyles: {
                0: { cellWidth: 50 },
                2: { halign: 'center' },
                3: { halign: 'right' },
                4: { halign: 'right' },
                5: { halign: 'right' },
                6: { halign: 'center' },
                7: { halign: 'right' },
                8: { halign: 'right' }
            },
            didDrawPage: function(data) {
                // Footer on each page
                doc.setFontSize(8);
                doc.setTextColor(148, 163, 184);
                doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageWidth - 14, pageHeight - 10, { align: 'right' });
                doc.text('Confidential - Bee ERP System', 14, pageHeight - 10);
            }
        });
        
        // Final Summary after table
        const finalY = doc.lastAutoTable.finalY || 75;
        
        if (finalY + 40 < pageHeight) {
            doc.setFillColor(16, 185, 129); // Green
            doc.rect(10, finalY + 8, (pageWidth - 30) / 3, 20, 'F');
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(10);
            doc.setFont(undefined, 'bold');
            doc.text('TOTAL STOCK VALUE', 15, finalY + 16);
            doc.setFontSize(14);
            doc.text(formatCurrency(grandTotal), 15, finalY + 24);

            doc.setFillColor(245, 158, 11); // Amber
            doc.rect(10 + (pageWidth - 30) / 3 + 5, finalY + 8, (pageWidth - 30) / 3, 20, 'F');
            doc.setFontSize(10);
            doc.setFont(undefined, 'bold');
            doc.text('TOTAL RETURNS', 15 + (pageWidth - 30) / 3 + 5, finalY + 16);
            doc.setFontSize(14);
            doc.text(formatCurrency(totalReturned), 15 + (pageWidth - 30) / 3 + 5, finalY + 24);

            doc.setFillColor(239, 68, 68); // Red
            doc.rect(10 + 2 * ((pageWidth - 30) / 3 + 5), finalY + 8, (pageWidth - 30) / 3, 20, 'F');
            doc.setFontSize(10);
            doc.setFont(undefined, 'bold');
            doc.text('TOTAL DAMAGES', 15 + 2 * ((pageWidth - 30) / 3 + 5), finalY + 16);
            doc.setFontSize(14);
            doc.text(formatCurrency(totalDamaged), 15 + 2 * ((pageWidth - 30) / 3 + 5), finalY + 24);
        }
        
        const pdfBytes = doc.output('arraybuffer');
        const filename = department === 'all' 
            ? 'stock_valuation_report_all.pdf'
            : `stock_valuation_report_${department}.pdf`;

        return new Response(pdfBytes, {
            status: 200,
            headers: { 
                'Content-Type': 'application/pdf', 
                'Content-Disposition': `attachment; filename=${filename}` 
            }
        });

    } catch (error) {
        console.error('Error generating report:', error);
        return Response.json({ error: error.message }, { status: 500 });
    }
});